use std::env;
use std::sync::LazyLock;

#[derive(Clone, Copy)]
pub enum Lang { En, Ru, De }

static LANG: LazyLock<Lang> = LazyLock::new(|| {
    for var in ["LC_ALL", "LC_MESSAGES", "LANG", "LANGUAGE"] {
        if let Ok(val) = env::var(var) {
            let v = val.to_lowercase();
            if v.starts_with("ru") { return Lang::Ru; }
            if v.starts_with("de") { return Lang::De; }
        }
    }
    Lang::En
});

// (en, ru, de)
static T: &[(&str, &str, &str)] = &[
    // ── справка / usage ───────────────────────────────────────────────────────
    ("Usage:", "Использование:", "Verwendung:"),
    ("  nymphalis <service> <command> [args...]",
     "  nymphalis <сервис> <команда> [аргументы...]",
     "  nymphalis <Dienst> <Befehl> [Argumente...]"),
    ("Services:", "Сервисы:", "Dienste:"),
    ("  gelbooru.com  (aliases: gelbu, gel, gelbooru)",
     "  gelbooru.com  (псевдонимы: gelbu, gel, gelbooru)",
     "  gelbooru.com  (Aliase: gelbu, gel, gelbooru)"),
    ("  desu.uno      (aliases: desu)",
     "  desu.uno      (псевдонимы: desu)",
     "  desu.uno      (Aliase: desu)"),
    ("Global commands:", "Глобальные команды:", "Globale Befehle:"),
    ("  nymphalis set <variable> <value>",
     "  nymphalis set <переменная> <значение>",
     "  nymphalis set <Variable> <Wert>"),
    ("      Save a setting into {} . Variables: user_id, api_key, jobs.",
     "      Сохранить настройку в {} . Переменные: user_id, api_key, jobs.",
     "      Einstellung speichern in {} . Variablen: user_id, api_key, jobs."),
    ("  nymphalis version",
     "  nymphalis version",
     "  nymphalis version"),
    ("      Show version and platform.",
     "      Показать версию и платформу.",
     "      Version und Plattform anzeigen."),
    ("  nymphalis update",
     "  nymphalis update",
     "  nymphalis update"),
    ("      Check for the latest version on GitHub.",
     "      Проверить последнюю версию на GitHub.",
     "      Auf neueste Version auf GitHub prüfen."),
    ("Examples:", "Примеры:", "Beispiele:"),
    ("  nymphalis set user_id 1111111",
     "  nymphalis set user_id 1111111",
     "  nymphalis set user_id 1111111"),
    ("  nymphalis set api_key c76c2060...your_key...",
     "  nymphalis set api_key c76c2060...your_key...",
     "  nymphalis set api_key c76c2060...your_key..."),
    ("  nymphalis set jobs 8", "  nymphalis set jobs 8", "  nymphalis set jobs 8"),
    ("  nymphalis gelbooru.com search aeg",
     "  nymphalis gelbooru.com search aeg",
     "  nymphalis gelbooru.com search aeg"),
    ("  nymphalis gelbu download ./downloads cat blue_eyes",
     "  nymphalis gelbu download ./downloads cat blue_eyes",
     "  nymphalis gelbu download ./downloads cat blue_eyes"),
    ("  nymphalis desu.uno search gals",
     "  nymphalis desu.uno search gals",
     "  nymphalis desu.uno search gals"),
    ("  nymphalis desu download ./manga imaizumins-house-is-a-place-for-gals-to-gather.5467",
     "  nymphalis desu download ./manga imaizumins-house-is-a-place-for-gals-to-gather.5467",
     "  nymphalis desu download ./manga imaizumins-house-is-a-place-for-gals-to-gather.5467"),
    // ── общие ошибки ──────────────────────────────────────────────────────────
    ("Unknown service: {}\n", "Неизвестный сервис: {}\n", "Unbekannter Dienst: {}\n"),
    ("Unknown command for {}: {}\n",
     "Неизвестная команда для {}: {}\n",
     "Unbekannter Befehl für {}: {}\n"),
    ("Failed to build HTTP client: {}",
     "Не удалось создать HTTP-клиент: {}",
     "HTTP-Client-Fehler: {}"),
    ("Failed to serialize config: {}",
     "Не удалось сериализовать конфиг: {}",
     "Konfiguration konnte nicht serialisiert werden: {}"),
    ("Failed to write {}: {}", "Не удалось записать {}: {}", "Schreiben fehlgeschlagen {}: {}"),
    ("Failed to create directory '{}': {}",
     "Не удалось создать папку '{}': {}",
     "Verzeichnis '{}' konnte nicht erstellt werden: {}"),
    ("Cannot create {}: {}", "Не удалось создать {}: {}", "Erstellen fehlgeschlagen {}: {}"),
    ("Cancelled.", "Отменено.", "Abgebrochen."),
    ("Total", "Всего", "Gesamt"),
    ("{} ({}/s)", "{} ({}/с)", "{} ({}/s)"),
    // ── config set ────────────────────────────────────────────────────────────
    ("set requires exactly <variable> <value>.\n",
     "set требует ровно <переменная> <значение>.\n",
     "set erwartet genau <Variable> <Wert>.\n"),
    ("Unknown variable '{}'. Supported: user_id, api_key, desu_session, desu_proxy, patreon_session, patreon_proxy, jobs",
     "Неизвестная переменная '{}'. Поддерживаются: user_id, api_key, desu_session, desu_proxy, patreon_session, patreon_proxy, jobs",
     "Unbekannte Variable '{}'. Unterstützt: user_id, api_key, desu_session, desu_proxy, patreon_session, patreon_proxy, jobs"),
    ("jobs must be a positive integer.",
     "jobs должно быть положительным целым числом.",
     "jobs muss eine positive Ganzzahl sein."),
    ("Saved '{}' to {}", "Сохранено '{}' в {}", "'{}' gespeichert in {}"),
    // ── gelbooru / общее ──────────────────────────────────────────────────────
    ("Commands (gelbooru.com):", "Команды (gelbooru.com):", "Befehle (gelbooru.com):"),
    ("  nymphalis gelbooru.com download <dir> <tag1> [tag2] ...",
     "  nymphalis gelbooru.com download <папка> <тег1> [тег2] ...",
     "  nymphalis gelbooru.com download <Ordner> <Tag1> [Tag2] ..."),
    ("      Download all images for the given tags into <dir>.",
     "      Скачать все изображения по тегам в <папка>.",
     "      Alle Bilder für die angegebenen Tags in <Ordner> herunterladen."),
    ("  nymphalis gelbooru.com search <keyword>",
     "  nymphalis gelbooru.com search <ключевое_слово>",
     "  nymphalis gelbooru.com search <Suchbegriff>"),
    ("      Search for tags matching <keyword>.",
     "      Поиск тегов по <ключевое_слово>.",
     "      Tags passend zu <Suchbegriff> suchen."),
    ("  nymphalis gelbooru.com set user_id <value>",
     "  nymphalis gelbooru.com set user_id <значение>",
     "  nymphalis gelbooru.com set user_id <Wert>"),
    ("  nymphalis gelbooru.com set api_key <value>",
     "  nymphalis gelbooru.com set api_key <значение>",
     "  nymphalis gelbooru.com set api_key <Wert>"),
    ("      Save Gelbooru credentials to {}.",
     "      Сохранить учётные данные Gelbooru в {}.",
     "      Gelbooru-Zugangsdaten in {} speichern."),
    // ── gelbooru credentials ──────────────────────────────────────────────────
    ("Warning: GELBOORU_USER_ID / GELBOORU_API_KEY are not set",
     "Внимание: GELBOORU_USER_ID / GELBOORU_API_KEY не заданы",
     "Warnung: GELBOORU_USER_ID / GELBOORU_API_KEY nicht gesetzt"),
    ("(checked environment, .env, and {}).",
     "(проверены переменные окружения, .env и {}).",
     "(Umgebung, .env und {} wurden geprüft)."),
    ("Gelbooru now rejects anonymous API requests with 401 Unauthorized.",
     "Gelbooru теперь отклоняет анонимные запросы с кодом 401.",
     "Gelbooru lehnt anonyme API-Anfragen mit 401 ab."),
    ("Get your credentials at gelbooru.com -> My Account -> Options ->",
     "Получи учётные данные на gelbooru.com -> My Account -> Options ->",
     "Zugangsdaten unter gelbooru.com -> My Account -> Options ->"),
    ("API Access Credentials, then either:",
     "API Access Credentials, затем либо:",
     "API Access Credentials, dann entweder:"),
    ("  nymphalis set user_id 12345",
     "  nymphalis set user_id 12345",
     "  nymphalis set user_id 12345"),
    ("  nymphalis set api_key yourkey",
     "  nymphalis set api_key yourkey",
     "  nymphalis set api_key yourkey"),
    ("or export them as environment variables.",
     "либо экспортируй их как переменные окружения.",
     "oder als Umgebungsvariablen exportieren."),
    ("401 Unauthorized: Gelbooru requires API credentials for every",
     "401 Unauthorized: Gelbooru требует учётные данные для каждого",
     "401 Unauthorized: Gelbooru benötigt API-Zugangsdaten für jede"),
    ("request (anonymous access was disabled in 2025). Set:",
     "запроса (анонимный доступ отключён с 2025 года). Задай:",
     "Anfrage (anonymer Zugriff seit 2025 deaktiviert). Setze:"),
    ("  GELBOORU_USER_ID  and  GELBOORU_API_KEY",
     "  GELBOORU_USER_ID  и  GELBOORU_API_KEY",
     "  GELBOORU_USER_ID  und  GELBOORU_API_KEY"),
    ("(get them at gelbooru.com -> My Account -> Options ->",
     "(получи их на gelbooru.com -> My Account -> Options ->",
     "(unter gelbooru.com -> My Account -> Options ->"),
    ("API Access Credentials) and try again.",
     "API Access Credentials) и попробуй снова.",
     "API Access Credentials) und nochmal versuchen."),
    // ── gelbooru download ─────────────────────────────────────────────────────
    ("download requires a directory and at least one tag.\n",
     "download требует папку и хотя бы один тег.\n",
     "download benötigt einen Ordner und mindestens einen Tag.\n"),
    ("Tags: {}", "Теги: {}", "Tags: {}"),
    ("Output directory: {}", "Папка для сохранения: {}", "Ausgabeordner: {}"),
    ("API request error (page {}): {}",
     "Ошибка запроса к API (страница {}): {}",
     "API-Anfragefehler (Seite {}): {}"),
    ("API returned status {} on page {}",
     "API вернул статус {} на странице {}",
     "API antwortete mit Status {} auf Seite {}"),
    ("No images found for the given tags.",
     "По указанным тегам ничего не найдено.",
     "Keine Bilder für die angegebenen Tags gefunden."),
    ("No new images to download, everything is already on disk.",
     "Новых изображений нет, всё уже скачано.",
     "Keine neuen Bilder – alles bereits auf der Festplatte."),
    ("Checking file sizes...", "Проверка размеров файлов...", "Dateigrößen werden geprüft..."),
    ("Parallel workers: {}", "Параллельных потоков: {}", "Parallele Threads: {}"),
    ("About to download {} images (~{}). Continue? [y/N]: ",
     "Будет скачано {} изображений (~{}). Продолжить? [y/N]: ",
     "{} Bilder (~{}) werden heruntergeladen. Fortfahren? [y/N]: "),
    ("Done. Downloaded: {}, skipped (already existed): {}",
     "Готово. Скачано: {}, пропущено (уже было): {}",
     "Fertig. Heruntergeladen: {}, übersprungen (bereits vorhanden): {}"),
    ("request error: {}", "ошибка запроса: {}", "Anfragefehler: {}"),
    ("status {}", "статус {}", "Status {}"),
    ("create file: {}", "создание файла: {}", "Datei erstellen: {}"),
    ("read: {}", "чтение: {}", "Lesen: {}"),
    ("write: {}", "запись: {}", "Schreiben: {}"),
    ("rename file: {}", "переименование файла: {}", "Datei umbenennen: {}"),
    // ── gelbooru search ───────────────────────────────────────────────────────
    ("search expects exactly one keyword.\n",
     "search требует ровно одно ключевое слово.\n",
     "search erwartet genau einen Suchbegriff.\n"),
    ("API request error: {}", "Ошибка запроса к API: {}", "API-Anfragefehler: {}"),
    ("API returned status {}", "API вернул статус {}", "API antwortete mit Status {}"),
    ("Failed to read response: {}", "Не удалось прочитать ответ: {}", "Antwort konnte nicht gelesen werden: {}"),
    ("Failed to parse JSON: {}\nServer response: {}",
     "Не удалось распарсить JSON: {}\nОтвет сервера: {}",
     "JSON-Fehler: {}\nServerantwort: {}"),
    ("No tags found matching '{}'.",
     "Не найдено тегов, соответствующих '{}'.",
     "Keine Tags gefunden für '{}'."),
    ("Tags matching '{}':\n", "Теги по запросу '{}':\n", "Tags passend zu '{}':\n"),
    ("TAG", "ТЕГ", "TAG"),
    ("POSTS", "ПОСТОВ", "BEITRÄGE"),
    ("{} tags found. Use the exact tag name with: nymphalis gelbooru.com download <dir> <tag>",
     "Найдено тегов: {}. Используй точное имя: nymphalis gelbooru.com download <папка> <тег>",
     "{} Tags gefunden. Exakten Namen verwenden: nymphalis gelbooru.com download <Ordner> <Tag>"),
    // ── desu.uno – сервис ─────────────────────────────────────────────────────
    ("Commands (desu.uno):", "Команды (desu.uno):", "Befehle (desu.uno):"),
    ("  nymphalis desu.uno download <dir> <slug.id> [slug.id2] ...",
     "  nymphalis desu.uno download <папка> <slug.id> [slug.id2] ...",
     "  nymphalis desu.uno download <Ordner> <slug.id> [slug.id2] ..."),
    ("  nymphalis desu.uno download [manga|ranobe] <dir> <slug.id> [slug.id2] ...",
     "  nymphalis desu.uno download [manga|ranobe] <папка> <slug.id> [slug.id2] ...",
     "  nymphalis desu.uno download [manga|ranobe] <Ordner> <slug.id> [slug.id2] ..."),
    ("      Download all chapters of the given manga title(s) into <dir>.",
     "      Скачать все главы указанной манги в <папка>.",
     "      Alle Kapitel des Manga in <Ordner> herunterladen."),
    ("      Download all chapters of the given title(s) into <dir> (default: manga).",
     "      Скачать все главы указанных тайтлов в <папка> (по умолчанию: manga).",
     "      Alle Kapitel der angegebenen Titel in <Ordner> herunterladen (Standard: manga)."),
    ("  nymphalis desu.uno search <keyword>",
     "  nymphalis desu.uno search <ключевое_слово>",
     "  nymphalis desu.uno search <Suchbegriff>"),
    ("      Search for manga. Output: Human Title | slug.id",
     "      Поиск манги. Вывод: Название | slug.id",
     "      Manga suchen. Ausgabe: Titel | slug.id"),
    ("  nymphalis desu.uno login [browser]",
     "  nymphalis desu.uno login [браузер]",
     "  nymphalis desu.uno login [Browser]"),
    ("      Open browser login page and save xf_session cookie automatically.",
     "      Открыть страницу входа и автоматически сохранить xf_session.",
     "      Browser-Login öffnen und xf_session automatisch speichern."),
    ("      Supported browsers: firefox, chromium, chrome, brave, falkon.",
     "      Поддерживаемые браузеры: firefox, chromium, chrome, brave, falkon.",
     "      Unterstützte Browser: firefox, chromium, chrome, brave, falkon."),
    // ── desu.uno – download / search ─────────────────────────────────────────
    ("download requires at least one manga title.\n",
     "download требует хотя бы одно название манги.\n",
     "download benötigt mindestens einen Manga-Titel.\n"),
    ("download ranobe requires an output directory and at least one title.\n",
     "download ranobe требует указать папку и хотя бы одно название ранобэ.\n",
     "download ranobe benötigt einen Ordner und mindestens einen Ranobe-Titel.\n"),
    ("Invalid ranobe id format: '{}'. Expected numeric id or 'slug.id'.",
     "Неверный формат id ранобэ: '{}'. Ожидается число или 'slug.id'.",
     "Ungültiges Ranobe-ID-Format: '{}'. Nummerische ID oder 'slug.id' erwartet."),
    ("Failed to fetch ranobe chapters for id {}: {}",
     "Не удалось получить список глав ранобэ для id {}: {}",
     "Kapitelliste für Ranobe-ID {} konnte nicht abgerufen werden: {}"),
    ("No chapters found for ranobe id {}.",
     "Главы для ранобэ id {} не найдены.",
     "Keine Kapitel für Ranobe-ID {} gefunden."),
    ("Downloading ranobe '{}': {} chapter(s)",
     "Скачивание ранобэ '{}': {} глав(ы)",
     "Ranobe '{}' herunterladen: {} Kapitel"),
    ("No manga found matching '{}'.",
     "Манга по запросу '{}' не найдена.",
     "Kein Manga gefunden für '{}'."),
    ("Manga matching '{}':\n", "Манга по запросу '{}':\n", "Manga passend zu '{}':\n"),
    ("HUMAN TITLE", "НАЗВАНИЕ", "TITEL"),
    ("SYSTEM ID", "СИСТЕМНЫЙ ID", "SYSTEM-ID"),
    ("{} results. Use the id/slug.id with: nymphalis desu.uno download <slug.id>",
     "Найдено: {}. Используй id/slug.id: nymphalis desu.uno download <slug.id>",
     "{} Ergebnisse. ID verwenden: nymphalis desu.uno download <slug.id>"),
    ("Invalid manga id format: '{}'. Expected numeric id or 'slug.id'.",
     "Неверный формат id манги: '{}'. Ожидается число или 'slug.id'.",
     "Ungültiges Manga-ID-Format: '{}'. Erwartet: Zahl oder 'slug.id'."),
    ("Failed to fetch manga info for id {}: {}",
     "Не удалось получить информацию о манге {}: {}",
     "Manga-Info für ID {} konnte nicht abgerufen werden: {}"),
    ("No chapters found for '{}'.", "Главы для '{}' не найдены.", "Keine Kapitel für '{}' gefunden."),
    ("Downloading '{}': {} chapter(s)", "Скачивание '{}': {} глав(ы)", "Herunterladen '{}': {} Kapitel"),
    ("About to download {} chapter(s). Continue? [y/N]: ",
     "Будет скачано {} глав(ы). Продолжить? [y/N]: ",
     "{} Kapitel werden heruntergeladen. Fortfahren? [y/N]: "),
    ("Failed to fetch pages for chapter {}: {}",
     "Не удалось получить страницы для главы {}: {}",
     "Seiten für Kapitel {} konnten nicht abgerufen werden: {}"),
    ("No pages in chapter {}.", "Страниц в главе {} не найдено.", "Kapitel {} hat keine Seiten."),
    ("Chapter {}/{}", "Глава {}/{}", "Kapitel {}/{}"),
    ("Done. {} chapter(s) downloaded.",
     "Готово. Скачано {} глав(ы).",
     "Fertig. {} Kapitel heruntergeladen."),
    ("Failed to fetch chapters for '{}': {}",
     "Не удалось получить главы для '{}': {}",
     "Kapitel für '{}' konnten nicht abgerufen werden: {}"),
    // ── desu.uno – login ──────────────────────────────────────────────────────
    ("Opening {} for desu.uno login...",
     "Открываю {} для входа на desu.uno...",
     "{} für desu.uno-Anmeldung öffnen..."),
    ("Log in with your account, then press Enter here.",
     "Войди в аккаунт, затем нажми Enter здесь.",
     "Im Browser anmelden, dann hier Enter drücken."),
    ("Reading session from browser cookie database...",
     "Читаю сессию из базы cookies браузера...",
     "Sitzung aus Browser-Cookie-Datenbank lesen..."),
    ("Could not find xf_session cookie in {}.",
     "Не удалось найти xf_session cookie в {}.",
     "xf_session-Cookie in {} nicht gefunden."),
    ("Make sure you completed the login and the page fully loaded.",
     "Убедись, что вход выполнен и страница полностью загрузилась.",
     "Sicherstellen, dass die Anmeldung abgeschlossen und die Seite vollständig geladen ist."),
    ("Session found but verification failed — the cookie may be stale.",
     "Сессия найдена, но верификация не прошла — cookie могла устареть.",
     "Sitzung gefunden, aber Verifikation fehlgeschlagen – Cookie möglicherweise abgelaufen."),
    ("Make sure you actually completed the login in the browser.",
     "Убедись, что вход в браузере действительно завершён.",
     "Sicherstellen, dass die Browseranmeldung tatsächlich abgeschlossen ist."),
    ("Could not find a valid session in any browser.",
     "Не удалось найти рабочую сессию ни в одном браузере.",
     "In keinem Browser wurde eine gültige Sitzung gefunden."),
    ("Make sure you are logged in on desu.uno in your browser.",
     "Убедись, что ты залогинен на desu.uno в браузере.",
     "Sicherstellen, dass du in deinem Browser auf desu.uno eingeloggt bist."),
    ("Or specify the browser: nymphalis desu login <browser>",
     "Или укажи браузер: nymphalis desu login <браузер>",
     "Oder Browser angeben: nymphalis desu login <Browser>"),
    ("Supported: firefox, chromium, chrome, brave, falkon",
     "Поддерживаются: firefox, chromium, chrome, brave, falkon",
     "Unterstützt: firefox, chromium, chrome, brave, falkon"),
    ("Manual fallback:", "Вручную:", "Manuell:"),
    ("  1. Open DevTools on desu.uno (F12)",
     "  1. Открой DevTools на desu.uno (F12)",
     "  1. DevTools auf desu.uno öffnen (F12)"),
    ("  2. Application → Cookies → desu.uno → xf_session → copy Value",
     "  2. Application → Cookies → desu.uno → xf_session → скопируй Value",
     "  2. Application → Cookies → desu.uno → xf_session → Wert kopieren"),
    ("  3. nymphalis set desu_session xf_session=<value>",
     "  3. nymphalis set desu_session xf_session=<значение>",
     "  3. nymphalis set desu_session xf_session=<Wert>"),
    ("Logged in as: {}", "Вошёл как: {}", "Angemeldet als: {}"),
    ("Session saved. Restricted content is now accessible.",
     "Сессия сохранена. Закрытый контент теперь доступен.",
     "Sitzung gespeichert. Eingeschränkte Inhalte sind jetzt zugänglich."),
    ("  (found valid session in {})",
     "  (найдена рабочая сессия в {})",
     "  (gültige Sitzung in {} gefunden)"),
    ("Could not launch '{}' automatically.",
     "Не удалось запустить '{}' автоматически.",
     "'{}' konnte nicht automatisch gestartet werden."),
    ("Please open this URL manually: {}",
     "Открой URL вручную: {}",
     "Bitte diese URL manuell öffnen: {}"),
    ("Unknown browser: '{}'. Supported: firefox, chromium, chrome, brave, falkon.",
     "Неизвестный браузер: '{}'. Поддерживаются: firefox, chromium, chrome, brave, falkon.",
     "Unbekannter Browser: '{}'. Unterstützt: firefox, chromium, chrome, brave, falkon."),
    // ── desu.uno – ошибки HTTP ────────────────────────────────────────────────
    ("HTTP 451 — title blocked by Roskomnadzor (149-FZ). Use 'search' to find an available slug.id.",
     "HTTP 451 — этот тайтл заблокирован по решению Роскомнадзора (149-ФЗ). Найди slug.id через 'search'.",
     "HTTP 451 — Titel durch Roskomnadzor gesperrt (149-FZ). Verfügbaren slug.id über 'search' finden."),
    ("HTTP 403 — access denied (login may be required).",
     "HTTP 403 — доступ запрещён (возможно, требуется авторизация).",
     "HTTP 403 — Zugriff verweigert (Anmeldung möglicherweise erforderlich)."),
    ("HTTP 404 — title not found. Check slug.id via 'search'.",
     "HTTP 404 — тайтл не найден. Проверь slug.id через 'search'.",
     "HTTP 404 — Titel nicht gefunden. slug.id über 'search' prüfen."),
    ("HTTP {}", "HTTP {}", "HTTP {}"),
    ("Unknown command for mangadex.org: {}",
     "Неизвестная команда для mangadex.org: {}",
     "Unbekannter Befehl für mangadex.org: {}"),
    ("Unknown command for patreon.com: {}\n",
     "Неизвестная команда для patreon.com: {}\n",
     "Unbekannter Befehl für patreon.com: {}\n"),
    ("download requires <dir> <manga-uuid> [uuid2 ...]",
     "download требует <папка> <manga-uuid> [uuid2 ...]",
     "download benötigt <Ordner> <manga-uuid> [uuid2 ...]"),
    // ── mangadex ──────────────────────────────────────────────────────────────
    ("Commands (mangadex.org):", "Команды (mangadex.org):", "Befehle (mangadex.org):"),
    ("  nymphalis md search <keyword>",
     "  nymphalis md search <ключевое_слово>",
     "  nymphalis md search <Suchbegriff>"),
    ("      Search manga with Russian translation available.",
     "      Поиск манги с русским переводом.",
     "      Manga mit russischer Übersetzung suchen."),
    ("  nymphalis md download <dir> <manga-uuid> [uuid2 ...]",
     "  nymphalis md download <папка> <manga-uuid> [uuid2 ...]",
     "  nymphalis md download <Ordner> <manga-uuid> [uuid2 ...]"),
    ("      Download all Russian chapters into <dir>/<uuid>/.",
     "      Скачать все русские главы в <папка>/<uuid>/.",
     "      Alle russischen Kapitel in <Ordner>/<uuid>/ herunterladen."),
    ("search requires a keyword.", "search требует ключевое слово.", "search benötigt einen Suchbegriff."),
    ("Search failed: {}", "Поиск не удался: {}", "Suche fehlgeschlagen: {}"),
    ("No manga found for '{}'.", "Манга '{}' не найдена.", "Kein Manga gefunden für '{}'."),
    ("\nManga search results for '{}':\n",
     "\nМанга по запросу '{}':\n",
     "\nManga-Suchergebnisse für '{}':\n"),
    ("TITLE", "НАЗВАНИЕ", "TITEL"),
    ("UUID", "UUID", "UUID"),
    ("Found: {}.", "Найдено: {}.", "Gefunden: {}."),
    ("Use uuid with: nymphalis md download <dir> <uuid>",
     "Используй uuid: nymphalis md download <папка> <uuid>",
     "UUID verwenden: nymphalis md download <Ordner> <uuid>"),
    ("Failed to fetch manga '{}': {}",
     "Не удалось получить мангу '{}': {}",
     "Manga '{}' konnte nicht abgerufen werden: {}"),
    ("Failed to get chapters for '{}': {}",
     "Не удалось получить главы '{}': {}",
     "Kapitel für '{}' konnten nicht abgerufen werden: {}"),
    ("No Russian chapters for '{}'.",
     "Нет русских глав для '{}'.",
     "Keine russischen Kapitel für '{}'."),
    ("  Chapter {}/{} server error: {}",
     "  Глава {}/{} — ошибка сервера: {}",
     "  Kapitel {}/{} Serverfehler: {}"),
    ("done", "готово", "fertig"),
    // ── patreon ───────────────────────────────────────────────────────────────
    ("Commands (patreon.com):", "Команды (patreon.com):", "Befehle (patreon.com):"),
    ("  nymphalis patreon login [browser]",
     "  nymphalis patreon login [браузер]",
     "  nymphalis patreon login [Browser]"),
    ("      Open browser for Google login; session is read automatically.",
     "      Открыть браузер для входа через Google; сессия читается автоматически.",
     "      Browser für Google-Login öffnen; Sitzung wird automatisch eingelesen."),
    ("      browser: firefox, chromium, chrome, brave, falkon (default: system default)",
     "      браузер: firefox, chromium, chrome, brave, falkon (по умолчанию: системный)",
     "      Browser: firefox, chromium, chrome, brave, falkon (Standard: Systemstandard)"),
    ("  nymphalis patreon show",
     "  nymphalis patreon show",
     "  nymphalis patreon show"),
    ("      List all active subscriptions.",
     "      Показать все активные подписки.",
     "      Alle aktiven Abonnements anzeigen."),
    ("  nymphalis patreon download <dir> <creator1> [creator2 ...]",
     "  nymphalis patreon download <папка> <автор1> [автор2 ...]",
     "  nymphalis patreon download <Ordner> <Ersteller1> [Ersteller2 ...]"),
    ("      Download all media from the given creator(s) into <dir>/<creator>/.",
     "      Скачать всё медиа от указанных авторов в <папка>.",
     "      Alle Medien der angegebenen Ersteller in <Ordner> herunterladen."),
    ("If automatic cookie reading fails, set the session manually:",
     "Если автоматическое чтение cookie не сработало, задай сессию вручную:",
     "Falls automatisches Cookie-Lesen fehlschlägt, Sitzung manuell setzen:"),
    ("  nymphalis set patreon_session session_id=<value>",
     "  nymphalis set patreon_session session_id=<значение>",
     "  nymphalis set patreon_session session_id=<Wert>"),
    ("Not logged in to Patreon. Run: nymphalis patreon login",
     "Не авторизован в Patreon. Выполни: nymphalis patreon login",
     "Nicht bei Patreon angemeldet. Ausführen: nymphalis patreon login"),
    ("Opening {} for Patreon login...",
     "Открываю {} для входа в Patreon...",
     "{} für Patreon-Anmeldung öffnen..."),
    ("Click \"Continue with Google\" and complete the login.",
     "Нажми «Continue with Google» и заверши вход.",
     "\"Continue with Google\" klicken und Anmeldung abschließen."),
    ("After you are redirected to your Patreon feed, press Enter here.",
     "После перехода на ленту Patreon нажми Enter здесь.",
     "Nach der Weiterleitung zum Patreon-Feed hier Enter drücken."),
    ("Could not find the session_id cookie automatically.",
     "Не удалось найти cookie session_id автоматически.",
     "Cookie session_id konnte nicht automatisch gefunden werden."),
    ("Make sure the browser has fully finished loading the Patreon page.",
     "Убедись, что браузер полностью загрузил страницу Patreon.",
     "Sicherstellen, dass der Browser die Patreon-Seite vollständig geladen hat."),
    ("  1. Open DevTools on patreon.com (F12)",
     "  1. Открой DevTools на patreon.com (F12)",
     "  1. DevTools auf patreon.com öffnen (F12)"),
    ("  2. Application → Cookies → www.patreon.com → session_id → copy Value",
     "  2. Application → Cookies → www.patreon.com → session_id → скопируй Value",
     "  2. Application → Cookies → www.patreon.com → session_id → Wert kopieren"),
    ("  3. nymphalis set patreon_session session_id=<value>",
     "  3. nymphalis set patreon_session session_id=<значение>",
     "  3. nymphalis set patreon_session session_id=<Wert>"),
    ("Warning: session found but verification failed: {}",
     "Внимание: сессия найдена, но верификация не прошла: {}",
     "Warnung: Sitzung gefunden, aber Verifikation fehlgeschlagen: {}"),
    ("Saving anyway — run 'patreon show' to check.",
     "Сохраняю всё равно — проверь через 'patreon show'.",
     "Trotzdem speichern – mit 'patreon show' prüfen."),
    ("Session saved.", "Сессия сохранена.", "Sitzung gespeichert."),
    ("Using proxy: {}", "Использую прокси: {}", "Proxy wird verwendet: {}"),
    ("Invalid proxy URL '{}': {}", "Некорректный URL прокси '{}': {}", "Ungültige Proxy-URL '{}': {}"),
    ("session expired or not logged in — run: nymphalis patreon login",
     "сессия истекла или не авторизован — выполни: nymphalis patreon login",
     "Sitzung abgelaufen oder nicht angemeldet — ausführen: nymphalis patreon login"),
    ("JSON parse error: {}", "Ошибка разбора JSON: {}", "JSON-Fehler: {}"),
    ("Failed to fetch subscriptions: {}",
     "Не удалось получить подписки: {}",
     "Abonnements konnten nicht abgerufen werden: {}"),
    ("No active subscriptions found.",
     "Активных подписок не найдено.",
     "Keine aktiven Abonnements gefunden."),
    ("\nActive Patreon subscriptions:\n",
     "\nАктивные подписки Patreon:\n",
     "\nAktive Patreon-Abonnements:\n"),
    ("CREATOR", "АВТОР", "ERSTELLER"),
    ("VANITY", "VANITY", "VANITY"),
    ("AMOUNT", "СУММА", "BETRAG"),
    ("\nTotal: {} subscription(s).",
     "\nВсего: {} подписок.",
     "\nGesamt: {} Abonnement(s)."),
    ("Use the VANITY name with: nymphalis patreon download <dir> <vanity>",
     "Используй VANITY: nymphalis patreon download <папка> <vanity>",
     "VANITY-Namen verwenden: nymphalis patreon download <Ordner> <vanity>"),
    ("download requires <dir> and at least one creator name.",
     "download требует <папка> и хотя бы одного автора.",
     "download benötigt <Ordner> und mindestens einen Ersteller."),
    ("\nFetching campaign for '{}'...",
     "\nПолучаю кампанию для '{}'...",
     "\nKampagne für '{}' abrufen..."),
    ("  Campaign lookup failed for '{}': {}",
     "  Не удалось найти кампанию '{}': {}",
     "  Kampagnensuche für '{}' fehlgeschlagen: {}"),
    ("  Creator '{}' not found. Make sure you are subscribed and the name matches patreon.com/{}",
     "  Автор '{}' не найден. Убедись, что ты подписан, а имя совпадает с patreon.com/{}",
     "  Ersteller '{}' nicht gefunden. Sicherstellen, dass du abonniert bist und der Name mit patreon.com/{} übereinstimmt"),
    ("  Scan failed on page {}: {}", "  Ошибка сканирования на странице {}: {}", "  Scan auf Seite {} fehlgeschlagen: {}"),
    ("Scanning page {}…  {} new / {} on disk",
     "Сканирование страницы {}…  {} новых / {} на диске",
     "Seite {} scannen…  {} neu / {} auf der Festplatte"),
    ("  Nothing new for '{}' — {} file(s) already on disk.",
     "  Ничего нового для '{}' — {} файл(ов) уже на диске.",
     "  Nichts Neues für '{}' — {} Datei(en) bereits auf der Festplatte."),
    ("  No accessible media found for '{}'.",
     "  Доступных медиафайлов для '{}' не найдено.",
     "  Keine zugänglichen Medien für '{}' gefunden."),
    ("  {} new file(s) to download, {} already on disk.",
     "  {} новых файл(ов) для скачивания, {} уже на диске.",
     "  {} neue Datei(en) zum Herunterladen, {} bereits auf der Festplatte."),
    ("About to download {} file(s). Continue? [y/N]: ",
     "Будет скачано {} файл(ов). Продолжить? [y/N]: ",
     "{} Datei(en) werden heruntergeladen. Fortfahren? [y/N]: "),
    ("Done for '{}': {} downloaded, {} failed, {} skipped (already on disk).",
     "Готово для '{}': {} скачано, {} ошибок, {} пропущено (уже на диске).",
     "Fertig für '{}': {} heruntergeladen, {} fehlgeschlagen, {} übersprungen (bereits auf Festplatte)."),
    ("  URL: {}", "  URL: {}", "  URL: {}"),
    // ── update ────────────────────────────────────────────────────────────────
    ("Checking for latest release from GitHub...",
     "Проверка последней версии с GitHub...",
     "Suche nach neuester Version auf GitHub..."),
    ("Failed to check for updates: {}",
     "Не удалось проверить обновления: {}",
     "Fehler beim Prüfen auf Updates: {}"),
    ("GitHub API rate limit exceeded. Please try again later.",
     "Превышен лимит запросов к GitHub API. Попробуйте позже.",
     "GitHub-API-Ratenlimit überschritten. Bitte später versuchen."),
    ("GitHub API returned error: {}",
     "GitHub API вернул ошибку: {}",
     "GitHub-API antwortete mit Fehler: {}"),
    ("Failed to parse release information: {}",
     "Не удалось прочитать информацию о релизе: {}",
     "Release-Informationen konnten nicht verarbeitet werden: {}"),
    ("You are using the latest version: {} ({})",
     "У вас установлена актуальная версия: {} ({})",
     "Sie verwenden bereits die neueste Version: {} ({})"),
    ("Current version ({} {}) is newer than the latest release ({}).",
     "Текущая версия ({} {}) новее последнего релиза ({}).",
     "Aktuelle Version ({} {}) ist neuer als das neueste Release ({})."),
    ("A new version is available: {} (current: {} {})",
     "Доступна новая версия: {} (текущая: {} {})",
     "Eine neue Version ist verfügbar: {} (aktuell: {} {})"),
    ("Release", "Релиз", "Release"),
    ("Direct download link for your platform ({}):\n  {}",
     "Прямая ссылка для вашей платформы ({}):\n  {}",
     "Direkter Download-Link für Ihre Plattform ({}):\n  {}"),
    ("Release page", "Страница релиза", "Release-Seite"),
    ("Changelog", "Список изменений", "Änderungsprotokoll"),
    ("No compatible asset found for platform {}",
     "Не найден файл для платформы {}",
     "Keine passende Datei für Plattform {} gefunden"),
    ("Downloading {}...", "Скачивание {}...", "Herunterladen von {}..."),
    ("Failed to download asset: {}", "Не удалось скачать файл: {}", "Fehler beim Herunterladen: {}"),
    ("Failed to download asset: HTTP {}", "Не удалось скачать файл: HTTP {}", "Fehler beim Herunterladen: HTTP {}"),
    ("Downloaded to {}", "Скачано в {}", "Heruntergeladen nach {}"),
    ("Update automatically to {}? [y/N]: ",
     "Обновить автоматически до {}? [y/N]: ",
     "Automatisch auf {} aktualisieren? [y/N]: "),
    ("Successfully updated nymphalis to {}!",
     "nymphalis успешно обновлён до {}!",
     "Nymphalis wurde erfolgreich auf {} aktualisiert!"),
    ("Permission denied. Try running with sudo: sudo nymphalis update",
     "Отказано в доступе. Попробуйте запустить с sudo: sudo nymphalis update",
     "Keine Berechtigung. Versuchen Sie es mit sudo: sudo nymphalis update"),
    ("Failed to determine current executable path: {}",
     "Не удалось определить путь к текущему исполняемому файлу: {}",
     "Pfad der aktuellen ausführbaren Datei konnte nicht ermittelt werden: {}"),
    ("Failed to create temporary file: {}",
     "Не удалось создать временный файл: {}",
     "Temporäre Datei konnte nicht erstellt werden: {}"),
    ("Failed to replace executable: {}",
     "Не удалось заменить исполняемый файл: {}",
     "Ausführbare Datei konnte nicht ersetzt werden: {}"),
    ("Failed to set executable permissions: {}",
     "Не удалось установить права на исполнение: {}",
     "Ausführungsrechte konnten nicht gesetzt werden: {}"),
    ("Failed to write update: {}",
     "Не удалось записать обновление: {}",
     "Update konnte nicht geschrieben werden: {}"),
];

// берёт английскую строку — возвращает локализованную
pub fn tr(en: &str) -> String {
    let idx = match *LANG {
        Lang::En => return en.to_string(),
        Lang::Ru => 1,
        Lang::De => 2,
    };
    T.iter()
        .find(|(e, _, _)| *e == en)
        .map(|t| [t.0, t.1, t.2][idx].to_string())
        .unwrap_or_else(|| en.to_string())
}

// то же самое но с подстановкой {} аргументов
pub fn trf(en: &str, args: &[&dyn std::fmt::Display]) -> String {
    let mut s = tr(en);
    for a in args {
        if let Some(pos) = s.find("{}") {
            s.replace_range(pos..pos + 2, &a.to_string());
        }
    }
    s
}
